"""initial

Revision ID: 961ea7d38e2d
Revises: 005_add_skills_to_fte_mapping
Create Date: 2026-02-05 12:55:03.202337

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '961ea7d38e2d'
down_revision = '005_add_skills_to_fte_mapping'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_validity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('allocation_execution_id', sa.String(length=255), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('invalidated_datetime', sa.DateTime(), nullable=True),
    sa.Column('invalidated_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', name='uq_month_year')
    )
    op.create_index('idx_validity_month_year', 'allocation_validity', ['month', 'year'], unique=False)
    op.create_table('fte_allocation_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allocation_execution_id', sa.String(length=36), nullable=False),
    sa.Column('report_month', sa.String(length=15), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('main_lob', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('case_type', sa.String(length=255), nullable=False),
    sa.Column('call_type_id', sa.String(length=100), nullable=True),
    sa.Column('forecast_month', sa.String(length=15), nullable=False),
    sa.Column('forecast_year', sa.Integer(), nullable=False),
    sa.Column('forecast_month_label', sa.String(length=10), nullable=False),
    sa.Column('forecast_month_index', sa.Integer(), nullable=False),
    sa.Column('cn', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('opid', sa.String(length=50), nullable=True),
    sa.Column('primary_platform', sa.String(length=100), nullable=True),
    sa.Column('primary_market', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('original_state', sa.String(length=100), nullable=True),
    sa.Column('worktype', sa.String(length=255), nullable=True),
    sa.Column('new_work_type', sa.String(length=500), nullable=True),
    sa.Column('skills', sa.String(length=500), nullable=True),
    sa.Column('allocation_type', sa.String(length=20), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fte_mapping_forecast_month', 'fte_allocation_mapping', ['report_month', 'report_year', 'forecast_month_label'], unique=False)
    op.create_index('idx_fte_mapping_lob_state_case', 'fte_allocation_mapping', ['main_lob', 'state', 'case_type'], unique=False)
    op.create_index('idx_fte_mapping_query', 'fte_allocation_mapping', ['report_month', 'report_year', 'main_lob', 'state', 'case_type'], unique=False)
    op.create_index(op.f('ix_fte_allocation_mapping_allocation_execution_id'), 'fte_allocation_mapping', ['allocation_execution_id'], unique=False)
    op.create_index(op.f('ix_fte_allocation_mapping_cn'), 'fte_allocation_mapping', ['cn'], unique=False)
    op.create_table('history_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_log_id', sa.String(length=36), nullable=False),
    sa.Column('MainLOB', sa.String(length=255), nullable=False),
    sa.Column('State', sa.String(length=100), nullable=False),
    sa.Column('CaseType', sa.String(length=255), nullable=False),
    sa.Column('CaseID', sa.String(length=100), nullable=False),
    sa.Column('FieldName', sa.String(length=100), nullable=False),
    sa.Column('OldValue', sa.Text(), nullable=True),
    sa.Column('NewValue', sa.Text(), nullable=True),
    sa.Column('Delta', sa.Float(), nullable=True),
    sa.Column('MonthLabel', sa.String(length=15), nullable=True),
    sa.Column('CreatedDateTime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_change_field', 'history_change', ['FieldName'], unique=False)
    op.create_index('idx_change_history_log', 'history_change', ['history_log_id'], unique=False)
    op.create_index('idx_change_identifiers', 'history_change', ['MainLOB', 'State', 'CaseType', 'CaseID'], unique=False)
    op.create_index('idx_change_month', 'history_change', ['MonthLabel'], unique=False)
    op.create_index(op.f('ix_history_change_history_log_id'), 'history_change', ['history_log_id'], unique=False)
    op.create_table('history_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_log_id', sa.String(length=36), nullable=False),
    sa.Column('Month', sa.String(length=15), nullable=False),
    sa.Column('Year', sa.Integer(), nullable=False),
    sa.Column('ChangeType', sa.String(length=50), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('User', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('RecordsModified', sa.Integer(), nullable=False),
    sa.Column('SummaryData', sa.Text(), nullable=True),
    sa.Column('CreatedBy', sa.String(length=100), nullable=False),
    sa.Column('CreatedDateTime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_history_change_type', 'history_log', ['ChangeType', 'Timestamp'], unique=False)
    op.create_index('idx_history_log_id', 'history_log', ['history_log_id'], unique=False)
    op.create_index('idx_history_month_year', 'history_log', ['Month', 'Year', 'Timestamp'], unique=False)
    op.create_index('idx_history_user', 'history_log', ['User', 'Timestamp'], unique=False)
    op.create_index(op.f('ix_history_log_history_log_id'), 'history_log', ['history_log_id'], unique=True)
    op.drop_index(op.f('success_index'), table_name='django_q_task', mssql_where='([success]=(1))')
    op.drop_table('django_q_task')
    op.drop_index(op.f('chat_messag_convers_0a903c_idx'), table_name='chat_messages')
    op.drop_index(op.f('chat_messages_conversation_id_92832a0b'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('core_user_user_permissions_permission_id_35ccf601'), table_name='core_user_user_permissions')
    op.drop_index(op.f('core_user_user_permissions_user_id_085123d3'), table_name='core_user_user_permissions')
    op.drop_table('core_user_user_permissions')
    op.drop_index(op.f('chat_tool_e_message_c13bda_idx'), table_name='chat_tool_executions')
    op.drop_index(op.f('chat_tool_e_tool_na_cb1dae_idx'), table_name='chat_tool_executions')
    op.drop_index(op.f('chat_tool_executions_message_id_af57e066'), table_name='chat_tool_executions')
    op.drop_table('chat_tool_executions')
    op.drop_table('auth_group')
    op.drop_index(op.f('auth_group_permissions_group_id_b120cbf9'), table_name='auth_group_permissions')
    op.drop_index(op.f('auth_group_permissions_permission_id_84c5c92e'), table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_index(op.f('chat_conver_convers_a59d92_idx'), table_name='chat_conversation_contexts')
    op.drop_index(op.f('chat_conver_updated_464a0c_idx'), table_name='chat_conversation_contexts')
    op.drop_table('chat_conversation_contexts')
    op.drop_table('django_q_ormq')
    op.drop_index(op.f('idx_summary_current'), table_name='data_summary')
    op.drop_index(op.f('idx_summary_version'), table_name='data_summary')
    op.drop_table('data_summary')
    op.drop_table('VW_Centene_Headcount_Monthly')
    op.drop_table('django_migrations')
    op.drop_index(op.f('core_user_groups_group_id_fe8c697f'), table_name='core_user_groups')
    op.drop_index(op.f('core_user_groups_user_id_70b4d9b8'), table_name='core_user_groups')
    op.drop_table('core_user_groups')
    op.drop_table('django_content_type')
    op.drop_table('django_q_schedule')
    op.drop_index(op.f('chat_conver_user_id_9d8b1a_idx'), table_name='chat_conversations')
    op.drop_index(op.f('chat_conversations_user_id_944d5292'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_table('Vw_Centene_Forecast data')
    op.drop_table('Headcount1')
    op.drop_index(op.f('auth_permission_content_type_id_2f476e4b'), table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_index(op.f('django_admin_log_content_type_id_c4bce8eb'), table_name='django_admin_log')
    op.drop_index(op.f('django_admin_log_user_id_c564eba6'), table_name='django_admin_log')
    op.drop_table('django_admin_log')
    op.drop_table('core_user')
    op.drop_index(op.f('django_session_expire_date_a5c62663'), table_name='django_session')
    op.drop_table('django_session')
    op.add_column('allocationexecutionmodel', sa.Column('BenchAllocationCompleted', sa.Boolean(), nullable=False))
    op.add_column('allocationexecutionmodel', sa.Column('BenchAllocationCompletedAt', sa.DateTime(), nullable=True))
    op.alter_column('allocationexecutionmodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('allocationreportsmodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('allocationreportsmodel', 'UpdatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('forecastmodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('forecastmodel', 'UpdatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('forecastmonthsmodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('monthconfigurationmodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('monthconfigurationmodel', 'UpdatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('prodteamrostermodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('prodteamrostermodel', 'UpdatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('raw_data', 'created_on',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('raw_data', 'updated_on',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('rostermodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('rostermodel', 'UpdatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('rostertemplate', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('rostertemplate', 'UpdatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('skillingmodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('skillingmodel', 'UpdatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skillingmodel', 'UpdatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('skillingmodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('rostertemplate', 'UpdatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('rostertemplate', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('rostermodel', 'UpdatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('rostermodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('raw_data', 'updated_on',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('raw_data', 'created_on',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('prodteamrostermodel', 'UpdatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('prodteamrostermodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('monthconfigurationmodel', 'UpdatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('monthconfigurationmodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('forecastmonthsmodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('forecastmodel', 'UpdatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('forecastmodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('allocationreportsmodel', 'UpdatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('allocationreportsmodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('allocationexecutionmodel', 'CreatedDateTime',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.drop_column('allocationexecutionmodel', 'BenchAllocationCompletedAt')
    op.drop_column('allocationexecutionmodel', 'BenchAllocationCompleted')
    op.create_table('django_session',
    sa.Column('session_key', sa.NVARCHAR(length=40, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('expire_date', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name=op.f('PK__django_s__B3BA0F1FED6814B3'))
    )
    op.create_index(op.f('django_session_expire_date_a5c62663'), 'django_session', ['expire_date'], unique=False)
    op.create_table('core_user',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('password', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('last_login', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.NVARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.NVARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.NVARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('is_staff', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('is_active', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('date_joined', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False),
    sa.Column('portal_id', sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.NVARCHAR(length=254, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__core_use__3213E83F74169003'))
    )
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('action_time', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('django_admin_log_content_type_id_c4bce8eb_fk_django_content_type_id')),
    sa.ForeignKeyConstraint(['user_id'], ['core_user.id'], name=op.f('django_admin_log_user_id_c564eba6_fk_core_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__django_a__3213E83F7DB3B3B5'))
    )
    op.create_index(op.f('django_admin_log_user_id_c564eba6'), 'django_admin_log', ['user_id'], unique=False)
    op.create_index(op.f('django_admin_log_content_type_id_c4bce8eb'), 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('auth_permission_content_type_id_2f476e4b_fk_django_content_type_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__auth_per__3213E83FEAE389F6'))
    )
    op.create_index(op.f('auth_permission_content_type_id_2f476e4b'), 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('Headcount1',
    sa.Column('Capacity_External', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('Capacity_Internal', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('claim type', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Claims per Day', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('Claims per Hour', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('Client Forecast Month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_forecast', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Convert_Headcount', sa.DECIMAL(precision=18, scale=12), autoincrement=False, nullable=True),
    sa.Column('Date', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('FTE_Requirements', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('Headcount', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('Imported date', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('Process', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Productive Hours', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('Ramp', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('Shrinkage', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('utilization', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('Working Days', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('Vw_Centene_Forecast data',
    sa.Column('Capacity', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('Imported date', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('Month', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('Platform', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Process', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('States', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('chat_conversations',
    sa.Column('id', sa.CHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('title', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False),
    sa.Column('updated_at', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False),
    sa.Column('is_active', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core_user.id'], name=op.f('chat_conversations_user_id_944d5292_fk_core_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__chat_con__3213E83F8E877C3D'))
    )
    op.create_index(op.f('chat_conversations_user_id_944d5292'), 'chat_conversations', ['user_id'], unique=False)
    op.create_index(op.f('chat_conver_user_id_9d8b1a_idx'), 'chat_conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('django_q_schedule',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('func', sa.NVARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('hook', sa.NVARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('args', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('kwargs', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('schedule_type', sa.NVARCHAR(length=2, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('repeats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('next_run', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=True),
    sa.Column('task', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('name', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('minutes', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('cron', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('cluster', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('intended_date_kwarg', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__django_q__3213E83F01D85AD4'))
    )
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('model', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__django_c__3213E83FB15B1EC1'))
    )
    op.create_table('core_user_groups',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('core_user_groups_group_id_fe8c697f_fk_auth_group_id')),
    sa.ForeignKeyConstraint(['user_id'], ['core_user.id'], name=op.f('core_user_groups_user_id_70b4d9b8_fk_core_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__core_use__3213E83FFC2EA1AB'))
    )
    op.create_index(op.f('core_user_groups_user_id_70b4d9b8'), 'core_user_groups', ['user_id'], unique=False)
    op.create_index(op.f('core_user_groups_group_id_fe8c697f'), 'core_user_groups', ['group_id'], unique=False)
    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('app', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('name', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('applied', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__django_m__3213E83F9C935E36'))
    )
    op.create_table('VW_Centene_Headcount_Monthly',
    sa.Column('Actual HC', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('Claim type', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Claims per day', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('Client forecast', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Convert_Headcount', sa.DECIMAL(precision=18, scale=12), autoincrement=False, nullable=True),
    sa.Column('FTE_requirement', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('Imported date', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('Month', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('Shrinkage', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('Utilization', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('working days', sa.DECIMAL(precision=18, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('data_summary',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('summary_type', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('month', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_current', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('dataframe_json', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('created_on', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('updated_on', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__data_sum__3213E83FDFCA7F1A'))
    )
    op.create_index(op.f('idx_summary_version'), 'data_summary', ['summary_type', 'month', 'year', 'version'], unique=False)
    op.create_index(op.f('idx_summary_current'), 'data_summary', ['summary_type', 'month', 'year', 'is_current'], unique=False)
    op.create_table('django_q_ormq',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('key', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('payload', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('lock', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__django_q__3213E83F29D6BF1A'))
    )
    op.create_table('chat_conversation_contexts',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('active_report_type', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('current_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('context_data', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('turn_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.CHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], name=op.f('chat_conversation_contexts_conversation_id_33873b16_fk_chat_conversations_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__chat_con__3213E83FA8DF96EB'))
    )
    op.create_index(op.f('chat_conver_updated_464a0c_idx'), 'chat_conversation_contexts', ['updated_at'], unique=False)
    op.create_index(op.f('chat_conver_convers_a59d92_idx'), 'chat_conversation_contexts', ['conversation_id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('auth_group_permissions_group_id_b120cbf9_fk_auth_group_id')),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('auth_group_permissions_permission_id_84c5c92e_fk_auth_permission_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__auth_gro__3213E83FB49BD953'))
    )
    op.create_index(op.f('auth_group_permissions_permission_id_84c5c92e'), 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('auth_group_permissions_group_id_b120cbf9'), 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.NVARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__auth_gro__3213E83F4555DF07'))
    )
    op.create_table('chat_tool_executions',
    sa.Column('id', sa.CHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('tool_name', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('parameters', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('result', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('status', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('executed_at', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.CHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('chat_tool_executions_message_id_af57e066_fk_chat_messages_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__chat_too__3213E83FA0A54E7D'))
    )
    op.create_index(op.f('chat_tool_executions_message_id_af57e066'), 'chat_tool_executions', ['message_id'], unique=False)
    op.create_index(op.f('chat_tool_e_tool_na_cb1dae_idx'), 'chat_tool_executions', ['tool_name', 'status'], unique=False)
    op.create_index(op.f('chat_tool_e_message_c13bda_idx'), 'chat_tool_executions', ['message_id', 'executed_at'], unique=False)
    op.create_table('core_user_user_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('core_user_user_permissions_permission_id_35ccf601_fk_auth_permission_id')),
    sa.ForeignKeyConstraint(['user_id'], ['core_user.id'], name=op.f('core_user_user_permissions_user_id_085123d3_fk_core_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__core_use__3213E83FEB8DB9DC'))
    )
    op.create_index(op.f('core_user_user_permissions_user_id_085123d3'), 'core_user_user_permissions', ['user_id'], unique=False)
    op.create_index(op.f('core_user_user_permissions_permission_id_35ccf601'), 'core_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.CHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('role', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('content', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('metadata', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('created_at', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.CHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], name=op.f('chat_messages_conversation_id_92832a0b_fk_chat_conversations_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__chat_mes__3213E83F3935DDB3'))
    )
    op.create_index(op.f('chat_messages_conversation_id_92832a0b'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('chat_messag_convers_0a903c_idx'), 'chat_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('django_q_task',
    sa.Column('name', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('func', sa.NVARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('hook', sa.NVARCHAR(length=256, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('args', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('kwargs', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('result', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('started', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False),
    sa.Column('stopped', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False),
    sa.Column('success', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.NVARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('group', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cluster', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__django_q__3213E83F82FA7747'))
    )
    op.create_index(op.f('success_index'), 'django_q_task', ['group', 'name', 'func'], unique=False, mssql_where='([success]=(1))')
    op.drop_index(op.f('ix_history_log_history_log_id'), table_name='history_log')
    op.drop_index('idx_history_user', table_name='history_log')
    op.drop_index('idx_history_month_year', table_name='history_log')
    op.drop_index('idx_history_log_id', table_name='history_log')
    op.drop_index('idx_history_change_type', table_name='history_log')
    op.drop_table('history_log')
    op.drop_index(op.f('ix_history_change_history_log_id'), table_name='history_change')
    op.drop_index('idx_change_month', table_name='history_change')
    op.drop_index('idx_change_identifiers', table_name='history_change')
    op.drop_index('idx_change_history_log', table_name='history_change')
    op.drop_index('idx_change_field', table_name='history_change')
    op.drop_table('history_change')
    op.drop_index(op.f('ix_fte_allocation_mapping_cn'), table_name='fte_allocation_mapping')
    op.drop_index(op.f('ix_fte_allocation_mapping_allocation_execution_id'), table_name='fte_allocation_mapping')
    op.drop_index('idx_fte_mapping_query', table_name='fte_allocation_mapping')
    op.drop_index('idx_fte_mapping_lob_state_case', table_name='fte_allocation_mapping')
    op.drop_index('idx_fte_mapping_forecast_month', table_name='fte_allocation_mapping')
    op.drop_table('fte_allocation_mapping')
    op.drop_index('idx_validity_month_year', table_name='allocation_validity')
    op.drop_table('allocation_validity')
    # ### end Alembic commands ###